nombre  = input('Ingrese su nombre:')
apellido = input("Ingrese su apellidop:")
fechadenacimiento = input("Ingrese su fecha de nacimiento:")
sexo = input("Ingrese su sexo:")
print("#######################")
print(f"###### {nombre} #######")
print(f"######{apellido  }#####")
print(f"######{fechadenacimiento}###")
print(f"######{sexo}######")
print("#######################")